# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"
paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"
  /product/best/concentrate:
    get:
      operationId: "product.best_concentrate"
      tags:
        - "Product, Concentrate, Best"
      summary: "Returns the best concentrate based on pre-configured parameters."
      responses:
        "200":
          description: "success"

  